/*
 * Copyright (c) 2004-2009, Jean-Marc François. All Rights Reserved.
 * Licensed under the New BSD license.  See the LICENSE file.
 */
package be.ac.ulg.montefiore.run.jahmm;

/**
 * Observations generated by a Markovian process. Observations are not mutable.
 */
public interface Observation extends INumberFormatString {

    /**
     * Converts this Observation to a {@link java.lang.String String}.
     *
     * @return A descriptive string.
     */
    @Override
    public String toString();
}
