/*
 * Copyright (c) 2004-2009, Jean-Marc François. All Rights Reserved.
 * Licensed under the New BSD license.  See the LICENSE file.
 */
package be.ac.ulg.montefiore.run.jahmm;

import java.util.logging.Logger;

/**
 * This class can build <code>OpdfMultiGaussian</code> observation probability
 * functions.
 */
public class OpdfMultiGaussianFactory
        implements OpdfFactory<OpdfMultiGaussian> {

    private final int dimension;

    /**
     * Generates a new multivariate gaussian observation probability
     * distribution function.
     *
     * @param dimension The dimension of the vectors generated by this object.
     */
    public OpdfMultiGaussianFactory(int dimension) {
        this.dimension = dimension;
    }

    @Override
    public OpdfMultiGaussian factor() {
        return new OpdfMultiGaussian(dimension);
    }
    private static final Logger LOG = Logger.getLogger(OpdfMultiGaussianFactory.class.getName());
}
