package jahmm.observables;

import java.text.NumberFormat;
import java.util.logging.Logger;

/**
 * An observation generated by an OpdfDiscrete.
 *
 * @author kommusoft
 */
public class ObservationDiscrete<TDiscrete> extends ObservationBase<TDiscrete> {

    private static final Logger LOG = Logger.getLogger(ObservationDiscrete.class.getName());

    /**
     * This observation value.
     */
    public final TDiscrete value;

    /**
     *
     * @param value
     */
    public ObservationDiscrete(TDiscrete value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return value.toString();
    }

    @Override
    public String toString(NumberFormat nf) {
        return toString();
    }

    @Override
    public TDiscrete getTag() {
        return this.value;
    }

}
