package be.ac.ulg.montefiore.run.distributions;

import java.io.*;


/** 
 * This interface must be implemented by all the package's classes implementing
 * a mono-variate random distribution.  Distributions are not mutable.
 */
public interface RandomDistribution 
extends Serializable
{    
    /**
     * Generates a pseudo-random number.  The numbers generated by this function
     * are drawn according to the pseudo-random distribution described by the
     * object that implements it.
     *
     * @return A pseudo-random number.
     */
    public double generate();


    /**
     * Returns the probability (density) of a given number.
     *
     * @param n A number.
     */
    public double probability(double n);
}
